# Dependencies and docker images that can be used to setup a
# development environment for this app in combination with
# the information in Gemfile (gems, ruby version, etc).

dependencies:
  node: "16.16.0" # Keep in sync with package.json

# NOTE: Keep in sync with .circleci/config.yml
docker_services:
  postgres:
    image: "postgres:14.4-alpine"
    version: "14.4"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/pipeline/postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:6.0.9"
    options: "--publish 6379 -v $DATABASE_ROOT/pipeline/redis:/data"
    command: "redis-server --appendonly yes"
