docker_services:
  postgres:
    image: "postgres:14.4-alpine" # Keep in sync with .circleci/config.yml
    version: "14.4"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/pipeline/postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:6.2.3-alpine" # Keep in sync with .circleci/config.yml
    options: "--publish 6379 -v $DATABASE_ROOT/pipeline/redis:/data"
    command: "redis-server --appendonly yes"
