docker_services:
  postgres:
    image: "postgres:16.3-alpine" # Keep in sync with .github/workflows/ci.yml
    version: "16.3"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/pipeline/postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:6.2.6-alpine" # Keep in sync with .github/workflows/ci.yml
    options: "--publish 6379 -v $DATABASE_ROOT/pipeline/redis:/data"
    command: "redis-server --appendonly yes"
