# Dependencies and docker images that can be used to setup a
# development environment for this app in combination with
# the information in Gemfile (gems, ruby version, etc).

dependencies:
  node: # Keep in sync with package.json
    version: "16.15.1"
    checksum: "308aee7149c4092a53c87c28ef49e23a8d1606119e79ae68333062e2a1f94208"

# NOTE: Keep in sync with .circleci/config.yml
docker_services:
  postgres:
    image: "postgres:13.5"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/pipeline/postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:6.0.9"
    options: "--publish 6379 -v $DATABASE_ROOT/pipeline/redis:/data"
    command: "redis-server --appendonly yes"
