# NOTE: Also check config/initializers/redis.rb
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  <%
    sentinels = nil
    if ENV["USING_SENTINEL_URL"]
      sentinel_uri = URI(ENV["SENTINEL_URL"])
      redis_uri = URI(ENV["REDIS_URL"])
      sentinels = Resolv.getaddresses(sentinel_uri.host).map { { host: it, port: sentinel_uri.port } }
    else
      port = ENV["DEVBOX"] ? `service_port redis`.strip : 6379
      url = URI.parse(ENV["REDIS_URL"] || "redis://localhost:#{port}")
    end
 %>
<% if sentinels %>
  url:
  name: <%= sentinel_uri.path.delete_prefix("/") %>
  sentinels: <%= sentinels.to_json %>
  sentinel_username: <%= sentinel_uri.user %>
  sentinel_password: <%= sentinel_uri.password %>
<% else %>
  url: <%= url %>
<% end %>
  channel_prefix: pipeline_production
